import Head from 'next/head';
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return <div>
    <Head>
      <title>Duolingo Achievements</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Component {...pageProps} />
  </div>
}

export default MyApp
